### ISSUE TITLE
ilovethis 

### ISSUE THREAD

**Issue by xezzs01** [TheUnblockedHubOfficial/TheUnblockedHub#10]
bro i love u so much thanks for making this but do u have any pokemons roms i could use lol love u again bye

**Comment by TheUnblockedHubOfficial** [comment]
No Problem I'm glad you enjoy! Here are some links via google Internet Archive is a great place to look: [Click Here To View Links](https://www.google.com/search?q=archive.org+pokemon+games&sca_esv=567294360&rlz=1CAOUAQ_enUS1063&ei=6GwMZd9ep5mm1A_E0LnQDQ&ved=0ahUKEwjf8pzGjbyBAxWnjIkEHURoDtoQ4dUDCBA&uact=5&oq=archive.org+pokemon+games&gs_lp=Egxnd3Mtd2l6LXNlcnAiGWFyY2hpdmUub3JnIHBva2Vtb24gZ2FtZXMyBhAAGBYYHjIIEAAYigUYhgMyCBAAGIoFGIYDMggQABiKBRiGAzIIEAAYigUYhgMyCBAAGIoFGIYDSNcHUExYpgZwAXgBkAEAmAHXAaAB9gaqAQUxLjQuMbgBA8gBAPgBAcICChAAGEcY1gQYsAPCAgUQABiABOIDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp&safe=active&ssui=on)

**Comment by xinterstellar** [comment]
@xezzs01 this website's code was stolen from Interstellar Network (https://github.com/interstellarnetwork/interstellar)
