### ISSUE TITLE
website blocked with familyzone

### ISSUE THREAD

**Issue by megurger** [TheUnblockedHubOfficial/TheUnblockedHub#19]
website got blocked while I was at PE, and everyone was destroyed. I am requesting for either a new link or a copy of the hub, but im not sure how the filter works.

**Comment by megurger** [comment]
![Screenshot 2023-12-01 2 05 06 PM](https://github.com/TheUnblockedHubOfficial/TheUnblockedHub/assets/152659820/54891f0e-94e4-454c-9798-2d96fd6a8bbf)

**Comment by megurger** [comment]
I cant go to the alt links, nothing works

**Comment by TheUnblockedHubOfficial** [comment]
deploy your own ubh
