### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OutRed** [TheUnblockedHubOfficial/TheUnblockedHub#9]
Hey there!
Normally I would send this to your Discord server, but I did not see one after looking at your (skidded) website and GitHub. 

Not to long ago, I noticed this account created a fork of: https://GitHub.com/outred/outredgames

I went to go check it out, but it was a 404 page. According to the license, that repo cannot be modified unless it is to make a PR, and it cannot be made private. I don't know if you made it private, or if you deleted the fork.

If you made it private, please take it down or make it public. Remember, you are not allowed to make it private or modify. Please respond ASAP or I will be sending a DMCA takedown.

Cheers,
OutRed

**Comment by OutRed** [comment]
Forgot to say: if you do not respond within 1 week a DMCA takedown request will be sent to GitHub.

**Comment by TheUnblockedHubOfficial** [comment]
I took it down already and no
